name: Conditional workflow
on: workflow_dispatch
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - name: step-1
              run: echo "In step 1"

            - name: step-2
              if: failure()
              run: echo "In step 2"