name: Deployment (Container)
on: workflow_dispatch
env:
  CACHE_KEY: node-deps
  MONGODB_DB_NAME: github-demo
jobs:
  test:
    environment: testing
    runs-on: ubuntu-latest
    # container: #run this job inside container. 
    #   image: node:18
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb
      #MONGODB_CLUSTER_ADDRESS: mongodb # this value should be same as mongodb service name if you are running your job in container. 
      MONGODB_CLUSTER_ADDRESS: 127.0.0.1:27017 # use github runner local port
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
    # service containers
    services:
      mongodb:
        image: mongo
        ports: # use when you are not running your job into container. 
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: ${{ secrets.MONGODB_USERNAME }}
          MONGO_INITDB_ROOT_PASSWORD:  ${{ secrets.MONGODB_PASSWORD }}
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ env.CACHE_KEY }}-${{ hashFiles('**/container-app/package-lock.json') }}
      - name: Install dependencies
        run: |
          cd container-app
          npm install
      - name: Run server
        run: |
          cd container-app
          npm start & npx wait-on http://127.0.0.1:$PORT                                          
      - name: Run tests
        run: |
          cd container-app
          npm test
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        env:
          PORT: 3000
        run: |        
          echo "MONGODB_DB_NAME: $MONGODB_DB_NAME"
          echo "MONGODB_USERNAME: $MONGODB_USERNAME"
          echo "${{ env.PORT }}"
