name: Reusable deploy workflow
on: workflow_call
jobs:
    reusable-deploy-job:
        runs-on: ubuntu-latest
        steps:
            - name: Deploy application
              run: echo "Deploy application..."
