name: Reusable deploy workflow
on: 
    workflow_call:
        inputs: # define workflow inputs
          artifact-name:
            description: Name of the artifact
            type: string
            required: false
            default: artifacts
        secrets: # define workflow secrets
          some-secret:
            required: false
        outputs: # define workflow outputs
           reusable-workflow-outcome: 
            description: Output of the reusable worflow.
            value: ${{ jobs.reusable-deploy-job.outputs.result }}

jobs:
    reusable-deploy-job:
        outputs:
          result: ${{ steps.output-step.outputs.step-result}}
        runs-on: ubuntu-latest
        steps:
            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with: 
                name: ${{ inputs.artifact-name }}
            - name: Deploy application
              run: |
                echo "Deploy application..."
                echo "Secret Info - ${{ secrets.some-secret}}"
            - name: Return output
              id : output-step
              run: echo "::set-output name=step-result::success"
