name: Reusable deploy workflow
on: 
    workflow_call:
        inputs: # define workflow inputs
          artifact-name:
            description: Name of the artifact
            type: string
            required: false
            default: artifacts
        secrets: # define workflow secrets
          some-secret:
            required: false  
jobs:
    reusable-deploy-job:
        runs-on: ubuntu-latest
        steps:
            - name: Download build artifacts
              uses: actions/download-artifact@v4
              with: 
                name: ${{ inputs.artifact-name }}
            - name: Deploy application
              run: |
                echo "Deploy application..."
                echo "Secret Info - ${{ secrets.some-secret}}"
