name: Build and Deploy React application
on: push
jobs:
    test-job: # test react application
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4

            - name: Install NodeJs
              uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: Install dependencies
              run:  |
                cd second-action-react-app
                ls -la
                npm install
                npm test

    deploy-job: #Build and deploy application
        needs: [test-job] # deploy-job will run after successfully completion of test-job. 
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4

            - name: Install NodeJs
              uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: Install dependencies and Build application
              run:  |
                cd second-action-react-app
                ls -la
                npm install
                npm run build

            - name: Deploy application
              run: echo "Deploying application...."