name: Test React application
on: push
jobs:
    test-job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository code
              uses: actions/checkout@v4

            - name: Install NodeJs
              uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: Install dependencies
              run:  |
                cd second-action-react-app
                ls -la
                npm install
                npm test